### ISSUE TITLE
Storefront client not showing exact error instead showing invalid json

### ISSUE THREAD

**Issue by mehmehsloth** [Shopify/shopify-api-js#379]
# Issue summary

I tried running storefront client to fetch products from my store. I intentionally put wrong storefront token to check the error message. Apparently I got invalid json input error. 
Here's the snippet code I am running ( example code provided in documentation ).
```js
  const client = new Shopify.Clients.Storefront(
    shopifyShopName,
    storefrontToken,
  )
  try {
    const products = await client.query({
      data: {
        query: `query GetProducts($first: Int!, $query: String!) {
      products (first: $first, query: $query) {
        edges {
          node {
            id
            title
            descriptionHtml
          }
        }
      }
    }`,
        variables: {
          first: 1,
          query: 'a',
        },
      },
    })

    return products.body
  } catch (error) {
    console.log({ error })
    throw new Error(error.message)
  }

```

## Expected behavior
Error should be provided by shopify api. In this particular case it should something like token is not valid.

## Actual behavior
I was given error about invalid json response body.
```
error: HttpRequestError: Failed to make Shopify HTTP request: FetchError: invalid json response body at https://{my-shop-name}/api/unstable/graphql.json reason: Unex
pected end of JSON input
      at HttpRequestError.ShopifyError [as constructor] ({directory}/@shopify/shopify-api/dist/error.js:13:28)
      at new HttpRequestError ({directory}/@shopify/shopify-api/dist/error.js:79:42)
      at {directory}/@shopify/shopify-api/dist/clients/http_client/http_client.js:242:35
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
}

```
## Steps to reproduce the problem

1. Create new storefront client.
2. Try any request that fails ( enter invalid token or shopname ) 

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by mehmehsloth** [comment]
> The same issue is happening in my server `HttpRequestError: Failed to make Shopify HTTP request: FetchError: invalid json response body at https://wonderchefind.myshopify.com/admin/api/2022-07/graphql.json ` but with using the Admin API. Did someone found a solution for this?

Hi sorry for replying this late. This issue can be fixed usually by generating new token.
