### ISSUE TITLE
SQL `SCOPES` breaks auth when its length > 256

### ISSUE THREAD

**Issue by rohanrajpal** [Shopify/shopify-api-js#457]
# Issue summary

The following issue occurs with Postgresql adapter

If we set the access scopes to let's say
```
SHOPIFY_API_SCOPES=unauthenticated_read_product_listings,unauthenticated_write_checkouts,unauthenticated_write_customers,unauthenticated_read_customer_tags,unauthenticated_read_content,unauthenticated_read_product_tags,read_orders,read_products,read_script_tags,write_script_tags,read_legal_policies
```

^ Character length - 280
## Expected behavior

It should create the session & return

## Actual behavior

Following error is thrown

```node
[Nest] 33685  - 19/08/2022, 14:58:00     LOG [HTTP] GET /shopify/auth?hmac=c9e9d53150477b29af025d5e9ba74cef1ad59c42f36f6b5f0f39887647f4b93d&host=c3B1ci1zYW1wbGUtc3RvcmUubXlzaG9waWZ5LmNvbS9hZG1pbg&shop=spur-sample-store.myshopify.com&timestamp=1660901280 302 1092 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36 ::ffff:127.0.0.1
[Nest] 33685  - 19/08/2022, 14:58:11   ERROR [ExceptionsHandler] value too long for type character varying(255)
error: value too long for type character varying(255)
    at Parser.parseErrorMessage (/Users/rohanrajpal/Documents/spurchat/code/spur/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rohanrajpal/Documents/spurchat/code/spur/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rohanrajpal/Documents/spurchat/code/spur/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rohanrajpal/Documents/spurchat/code/spur/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

## Steps to reproduce the problem

1. Take the Shopify Starter Node App
2. Set scopes to more than 256 characters (example above)
3. Use `PostgreSQLSessionStorage`
4. Try to do OAuth

## Proposed solution

We can simply increase the limit to the maximum length the `SHOPIFY_API_SCOPES` field can go to. One thing to note is that this does not happen with SQLite storage, I'm surprised why is that the case.

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by rohanrajpal** [comment]
> 

Happy to help!
