### ISSUE TITLE
getEmbeddedAppUrl does not work when calling from checkout.liquid

### ISSUE THREAD

**Issue by jawills** [Shopify/shopify-api-js#609]
# Issue summary

Write a short description of the issue here ↓

The getEmbeddedAppURL throws `InvalidRequestError: Request does not contain a host query parameter` when the starting destination is `checkout.liquid`

## Expected behavior

getEmbeddedAppURL navigates to the correct endpoint when used from 

## Actual behavior

<details>
InvalidRequestError: Request does not contain a host query parameter
</details>
is thrown

## Steps to reproduce the problem

1. Add axios / callout to checkout.liquid
2. Call embedded app
3. Error is thrown

**Comment by jawills** [comment]
Stack Trace
```
InvalidRequestError: Request does not contain a host query parameter

  at InvalidRequestError.ShopifyError [as constructor] (/app/node_modules/@shopify/shopify-api/dist/error.js:13:28)
  at new InvalidRequestError (/app/node_modules/@shopify/shopify-api/dist/error.js:230:42)
  at Object.getEmbeddedAppUrl (/app/node_modules/@shopify/shopify-api/dist/utils/get-embedded-app-url.js:23:15)
  at file:///app/index.js:223:43
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by NomanHameed** [comment]
I'm creating shopify app it;s working fine on local with ngrok pipline but when1 deploy on heroku it return error 

` InvalidRequestError: Request does not contain a host query parameter
`
i'm trying to access 

`https://{app}.herokuapp.com/?shop={shop}.myshopify.com`

```
[shopify-app/INFO] Running ensureInstalledOnShop
/app/web/node_modules/@shopify/shopify-api/lib/error.js:13
var _this = _super.apply(this, tslib_1.__spreadArray([], tslib_1.__read(args), false)) || this;
`^`
InvalidRequestError: Request does not contain a host query parameter
at InvalidRequestError.ShopifyError [as constructor] (/app/web/node_modules/@shopify/shopify-api/lib/error.js:13:28)
at new InvalidRequestError (/app/web/node_modules/@shopify/shopify-api/lib/error.js:225:42)
at /app/web/node_modules/@shopify/shopify-api/lib/auth/get-embedded-app-url.js:28:31
at step (/app/web/node_modules/tslib/tslib.js:193:27)
at Object.next (/app/web/node_modules/tslib/tslib.js:174:57)
at fulfilled (/app/web/node_modules/tslib/tslib.js:164:62)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
``` 
```

**Comment by mkevinosullivan** [comment]
For an embedded app, the Shopify system will include a `host` parameter when accessing the embedded app from the Admin.  If attempting to access it directly, you'll need to include that `host` parameter.  (More [info](https://shopify.dev/docs/apps/tools/app-bridge/migrating-to-2#modify-your-app-to-use-the-host-parameter) on the `host` parameter.)

You can construct the `host` parameter by opening `node` v16+ from the command line and entering
```shell
btoa('{shop}.myshopify.com/admin')
```
replacing `{shop}` with your actual shop name.  This will output a block of text that you can then use when you're trying to access your heroku-hosted app directly.
```
https://{app}.herokuapp.com/?shop={shop}.myshopify.com&host={block_of_text_from_btoa}
```
