### ISSUE TITLE
Hard to debug downcompiled async/await syntax

### ISSUE THREAD

**Issue by patdx** [Shopify/shopify-api-js#657]
# Issue summary

The stack traces for shopify API are a bit on the obtuse side, for example I just ran into this:

- `@shopify/shopify-api` version: 6.0.2
- Node version: 18
- Operating system: Mac OS

```
Error: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: example.myshopify.com
    at CookieNotFound2.ShopifyError2 [as constructor] (worker.mjs:22123:28)
    at new CookieNotFound2 (worker.mjs:22284:42)
    at Object.<anonymous> (worker.mjs:31902:25)
    at step (worker.mjs:21866:25)
    at Object.next (worker.mjs:21813:20)
    at fulfilled (worker.mjs:21784:30)
```

This is kind of compounded by the fact that some issues must be debugged in a production configuration where source maps may not be available.

We can see that the source async await is downcompiled into generator syntax:

https://unpkg.com/browse/@shopify/shopify-api@6.0.2/lib/auth/oauth/oauth.js

## Expected behavior

See if it is actually necessary to downcompile the async/await syntax in the NPM library?

If it can be preserved as is, this will give more useful stack traces.

Async/await has been supported in Node since v8.

The oldest version of Node that is still in maintenance is v14.

Additionally, is is quite easy these days for the end user to downcompile async/await syntax for a runtime that does not support it.

**Comment by patdx** [comment]
Still relevant with the latest version of this library: https://unpkg.com/browse/@shopify/shopify-api@6.2.0/lib/auth/oauth/oauth.js

**Comment by patdx** [comment]
This is still relevant with the latest version of this library:

https://unpkg.com/browse/@shopify/shopify-api@7.0.0/lib/auth/oauth/oauth.js

Note that Node v14 is also end of life as today, the lowest version of Node that is still actively maintained is v16, which definitely has async/await support. like [every version of Node since v8](https://node.green/#ES2017-features-async-functions). Hope you can review your build settings. Thank you :)

**Comment by patdx** [comment]
Still relevant: https://unpkg.com/browse/@shopify/shopify-api@7.4.0/lib/auth/oauth/oauth.js

**Comment by patdx** [comment]
I think that every platform that Shopify supports also supports async/await syntax natively. So I think the transpilation does not bring any benefits and has several downsides:

- Heavier bundle size
- Slower code
- Harder to read and debug
- Dependency on tslib

**Comment by public** [comment]
I would like to add that using a pre async/await `target` results in stack traces that are more than obtuse, they frequently omit the actual code that called into the shopify library in the first place making debugging which code is having problems next to impossible without wrapping everything in your own try/catch blocks.

Even if you do want to wrap everything in try/catch, in a large code base finding them all can be challenging when the stack doesn't tell you which code actually made the call that went wrong.

**Comment by patdx** [comment]
I agree completely with @public's comment above: https://github.com/Shopify/shopify-api-js/issues/657#issuecomment-1669417748

The latest version of shopify-api package on NPM still has this issue: https://unpkg.com/browse/@shopify/shopify-api@8.0.1/lib/auth/oauth/oauth.js

**Comment by paulomarg** [comment]
Hey folks, thanks for your patience. As part of merging our repos / revamping the build process, we've also updated our TS target so hopefully this will be improved. Please let us know in https://github.com/Shopify/shopify-app-js if you still run into problems!
