### ISSUE TITLE
Graphql Error on production mode.

### ISSUE THREAD

**Issue by adventuretocode** [Shopify/shopify-api-js#739]
# Issue summary
I am make query to shop data same code and same version of all the local package to live environments.  

- `@shopify/shopify-api` version:  "@shopify/shopify-api": "^5.2.0",
- Node version:   node -v v17.9.0

- Operating system: Ubuntu 20

```
 GraphqlQueryError: GraphQL query returned errors
log    at GraphqlQueryError.ShopifyError [as constructor] (coderoot/my-app//node_modules/@shopify/shopify-api/dist/error.js:13:28)
log    at new GraphqlQueryError (coderoot/my-app//node_modules/@shopify/shopify-api/dist/error.js:156:28)
log    at GraphqlClient.<anonymous> (coderoot/my-app//node_modules/@shopify/shopify-api/dist/clients/graphql/graphql_client.js:43:35)
log    at step (coderoot/my-app//node_modules/tslib/tslib.js:144:27)
log    at Object.next (coderoot/my-app//node_modules/tslib/tslib.js:125:57)
log    at fulfilled (coderoot/my-app//node_modules/tslib/tslib.js:115:62)
log    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
log  response: { errors: [ [Object] ] }
log}
logInvalidJwtError: Failed to parse session token 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvdHJ5LXNob3AtZm9yLXRlc3QubXlzaG9waWZ5LmNvbVwvYWRtaW4iLCJkZXN0IjoiaHR0cHM6XC9cL3RyeS1zaG9wLWZvci10ZXN0Lm15c2hvcGlmeS5jb20iLCJhdWQiOiI4ODgwM2U5MDdmZDM5MmEzZTlmNzJmNDBmYzJlMTRhYyIsInN1YiI6IjgxMDUwNjk3OTMzIiwiZXhwIjoxNjc3NTAwODk5LCJuYmYiOjE2Nzc1MDA4MzksImlhdCI6MTY3NzUwMDgzOSwianRpIjoiYWJmZWNmMDctYzQwYi00ZTEwLThlM2YtNTdiN2FhYzM2YzU4Iiwic2lkIjoiMGU2MzhlYTc2N2RlMDFiYTJkMDA4M2FhNmFjZDJlMmYwMDFkZTEzNDY5NzUxYzYyZTFkZTM5M2IyZWMzZTVkYiJ9.mVSvNzVKLa--rIPgPcopdEUMroZV__xvI4evHcYhJ3M': jwt expired
log    at InvalidJwtError.ShopifyError [as constructor] (coderoot/my-app//node_modules/@shopify/shopify-api/dist/error.js:13:28)
log    at new InvalidJwtError (coderoot/my-app//node_modules/@shopify/shopify-api/dist/error.js:47:42)
log    at decodeSessionToken (coderoot/my-app//node_modules/@shopify/shopify-api/dist/utils/decode-session-token.js:23:15)
log    at Object.getCurrentSessionId (coderoot/my-app//node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:174:69)
log    at Object.<anonymous> (coderoot/my-app//node_modules/@shopify/shopify-api/dist/utils/load-current-session.js:19:46)
log    at step (coderoot/my-app//node_modules/tslib/tslib.js:144:27)
log    at Object.next (coderoot/my-app//node_modules/tslib/tslib.js:125:57)
log    at coderoot/my-app//node_modules/tslib/tslib.js:118:75
log    at new Promise (<anonymous>)
log    at Object.__awaiter (coderoot/my-app//node_modules/tslib/tslib.js:114:16)
```

## Expected behavior
``` const shop_qgql = await client.query({
    data: `{
      shop {
        name
        email
        billingAddress {
          id
          country
        }
      }
    }`,
  }); 


    console.log("shop_qgql  - data ",shop_qgql.body.data.shop)
    console.log("shop_qgql  - email ",shop_qgql.body.data.shop.email)
    console.log("shop_qgql  - Country ",shop_qgql.body.data.shop.billingAddress.country)

```
when try to comment out the above code then make request it was working fine.
i am getting the result data in local environment app 

## Actual behavior
- graphql query return the data.

fire the Error on as above mention the log 

GraphqlQueryError: GraphQL query returned errors.

## Steps to reproduce the problem

1. use the office repo. to create the node js app. using cli 2.0 
2.   "@shopify/shopify-api": "^5.2.0",

code repo for the express router 
```

import { Shopify } from "@shopify/shopify-api";

Route.get("/api/test", async (req, res,next) => {


 const shop_qgql = await client.query({
    data: `{
      shop {
        name
        email
        billingAddress {
          id
          country
        }
      }
    }`,
  });


}
```

this code return the data other  local and [Shopify GraphiQL App]( shopify-graphiql-app) fine but why 

how to get the more data log.

**Comment by adventuretocode** [comment]
i am access the customer email i need   
Protected customer data access
  Your access will be reviewed to make sure that your:

Data use matches the functionality described in your App Store Listing
App meets Shopify’s requirements to access protected customer data

![image](https://user-images.githubusercontent.com/114073623/221776099-63a57958-63e4-4a80-aa7f-c645de8d0607.png)
