### ISSUE TITLE
Error: Missing adapter implementation for 'abstractRuntimeString'

### ISSUE THREAD

**Issue by FlorianB385** [Shopify/shopify-api-js#764]
Hi! We would like to build an simple Shopify App in nuxt3. After installation and configuration, we call the shopifyApi function.  Then the error occurs. Some issue report says, that we import first "@shopify/shopify-api/adapters/node" but that didn't help either.
 
- `@shopify/shopify-api` version: 6.2.0
- Node version: 18.14.0
- Operating system: MacOs Venture 13.2.1

```
[nitro] [dev] [uncaughtException] Error: Missing adapter implementation for 'abstractRuntimeString' - make sure to import the appropriate adapter for your platform
    at abstractRuntimeString (/Users/florianbottmann/Documents/workspace/shopify-donation/node_modules/@shopify/shopify-api/runtime/platform/runtime-string.js:6:11)
    at shopifyApi (/Users/florianbottmann/Documents/workspace/shopify-donation/node_modules/@shopify/shopify-api/lib/index.js:50:117)
    at file:///Users/florianbottmann/Documents/workspace/shopify-donation/.nuxt/dev/index.mjs:676:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

```

**Comment by paper-krane** [comment]
Having this exact issue as well. Been scouring the Shopify docs to see if I missed anything to no avail.

**Comment by codeustad** [comment]
Still getting this error with `@shopify/shopify-api": "7.5.1`

```
ReferenceError: process is not defined
    at nodeRuntimeString (.../node_modules/@shopify/shopify-api/adapters/node/adapter.ts:92:18)
    at shopifyApi2 (.../node_modules/@shopify/shopify-api/lib/index.ts:77:62)
    at Object.fetch (.../server.ts:70:23)
    at ServiceWorkerGlobalScope.[kDispatchFetch] (.../node_modules/@miniflare/core/src/standards/event.ts:385:13)
    at /.../node_modules/@shopify/mini-oxygen/dist/mini-oxygen/server.js:146:24
```

**Comment by BYohann** [comment]
I want to confirm that it will work if you import the library as with an await inside a nitro plugin 

export default defineNitroPlugin(async (nitroApp) => {
  await import('@shopify/shopify-api/adapters/node')
})

This way, the adapter is registered and work for Nuxt server functions with Nitro

**Comment by skoulix** [comment]
> > > I want to confirm that it will work if you import the library as with an await inside a nitro plugin
> > > export default defineNitroPlugin(async (nitroApp) => { await import('@shopify/shopify-api/adapters/node') })
> > > This way, the adapter is registered and work for Nuxt server functions with Nitro
> > 
> > 
> > @BYohann
> > I'm doing it the exact same way in a Nitro plugin and still getting the same error => "Error: Missing adapter implementation for 'abstractRuntimeString'"
> > Is this way what you are currently using?
> > Thanks.
> 
> Create a middleware server like `server/middleware/shopifyAdapters.js` with:
> 
> ```
> export default defineEventHandler((event) => {
> import("@shopify/shopify-api/adapters/node");
> });
> ```
> 
> This worked for me

Thank you!
