### ISSUE TITLE
Getting statuscode 406 when calling auth.begin

### ISSUE THREAD

**Issue by Andi365** [Shopify/shopify-api-js#781]
# Issue summary

- `@shopify/shopify-api` version: 2023-01
- Node version: V19.8.1
- Operating system: ubuntu through WSL

```
// Paste any relevant logs here
```
[shopify-api/INFO] version 6.2.0, environment Node v19.8.1
[shopify-api/INFO] Completing OAuth | {shop: myshop.myshopify.com}
[shopify-api/DEBUG] OAuth request is valid, requesting access token | {shop: myshop.myshopify.com}
[shopify-api/INFO] Creating new session | {shop: myshop.myshopify.com, isOnline: false}
[shopify-api/INFO] Registering webhooks | {shop: myshop.myshopify.com}
---> Error at /auth/tokens HttpResponseError: Received an error response (406 Not Acceptable) from Shopify:
If you report this error, please include this id: eb06ef6c-36cc-4480-9cd5-a60fe646f6e1
    at NewHttpClient.throwFailedRequest (/home/github/node_modules/@shopify/shopify-api/lib/clients/http_client/http_client.js:193:23)
    at NewHttpClient.<anonymous> (/home/github/node_modules/@shopify/shopify-api/lib/clients/http_client/http_client.js:220:22)
    at Generator.next (<anonymous>)
    at fulfilled (/home/github/node_modules/tslib/tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: {
    code: 406,
    statusText: 'Not Acceptable',
    body: {},
    headers: {
      'Alt-Svc': [Array],
      'Cf-Cache-Status': [Array],
      'Cf-Ray': [Array],
      Connection: [Array],
      'Content-Security-Policy': [Array],
      'Content-Type': [Array],
      Date: [Array],
      Http_x_shopify_shop_api_call_limit: [Array],
      Nel: [Array],
      'Referrer-Policy': [Array],
      'Report-To': [Array],
      Server: [Array],
      'Server-Timing': [Array],
      'Strict-Transport-Security': [Array],
      'Transfer-Encoding': [Array],
      'X-Content-Type-Options': [Array],
      'X-Dc': [Array],
      'X-Download-Options': [Array],
      'X-Frame-Options': [Array],
      'X-Permitted-Cross-Domain-Policies': [Array],
      'X-Request-Id': [Array],
      'X-Shardid': [Array],
      'X-Shopid': [Array],
      'X-Shopify-Api-Version': [Array],
      'X-Shopify-Shop-Api-Call-Limit': [Array],
      'X-Shopify-Stage': [Array],
      'X-Sorting-Hat-Podid': [Array],
      'X-Sorting-Hat-Shopid': [Array],
      'X-Stats-Apiclientid': [Array],
      'X-Stats-Apipermissionid': [Array],
      'X-Stats-Userid': [Array],
      'X-Xss-Protection': [Array]
    }
  }
}

## Expected behavior

Auth flow should succeed and redirect my to index route.

## Actual behavior

I get thrown 406 error.

## Steps to reproduce the problem

1.
1.
1.

**Comment by Andi365** [comment]
Thank you for the feedback Kevin. 

So basically the apiversion was specified in my .env file like this: `SHOPIFY_API_VERSION="2023-01"` which made the error!
