### ISSUE TITLE
InvalidJwtError: Failed to parse session token 

### ISSUE THREAD

**Issue by Sky-bits** [Shopify/shopify-api-js#791]
# Issue summary
I am getting errors in server-side  InvalidJwtError: Failed to parse session token 

- `@shopify/shopify-api` version: 5.2.0
- Node version:  v17.9.0
- Operating system: Linux 

```
// Paste any relevant logs here
```
`node_modules/@shopify/shopify-api/dist/error.js:13
        var _this = _super.apply(this, tslib_1.__spreadArray([], tslib_1.__read(args), false)) || this;
                           ^

InvalidJwtError: Failed to parse session token 'ey0XXXXsCiw': jwt expired
    at InvalidJwtError.ShopifyError [as constructor] (/code_repo//node_modules/@shopify/shopify-api/dist/error.js:13:28)
    at new InvalidJwtError (/code_repo//node_modules/@shopify/shopify-api/dist/error.js:47:42)
    at decodeSessionToken (/code_repo//node_modules/@shopify/shopify-api/dist/utils/decode-session-token.js:23:15)
    at Object.getCurrentSessionId (/code_repo//node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:174:69)
    at Object.<anonymous> (/code_repo//node_modules/@shopify/shopify-api/dist/utils/load-current-session.js:19:46)
`
## Expected behavior
library should be valid for the auth session token. 

## Actual behavior
library not able to validate the session token 

## Steps to reproduce the problem

1. create a custom session with MongoDB
2. not all time show this issue. only in a few of the cases, i can see the server-side Errors.
4. do any activity in an app. 
5. you will see the error in the server console running.

**Comment by mkevinosullivan** [comment]
@Sky-bits Is there a reason you're using v5.2.0 of the API package, instead of using v6?
