### ISSUE TITLE
TypeError: scopesArray.map is not a function on v7.0

### ISSUE THREAD

**Issue by schapicool** [Shopify/shopify-api-js#841]
# Issue summary

- `@shopify/shopify-api` version: 7.0.1
- Node version:v14.21.3
- Operating system: macos

```
it seem like a bug on +shopify-api@7.0.0 , I meet a error that UnhandledPromiseRejectionWarning: TypeError: scopesArray.map is not a function in the AuthScopes when update this version shopify-api@7.0.0 

but the first time is ok it break on second time reload the page on localhost dev


log below
(node:69582) UnhandledPromiseRejectionWarning: TypeError: scopesArray.map is not a function
    at new AuthScopes (web/node_modules/.pnpm/@shopify+shopify-api@7.0.0/node_modules/@shopify/shopify-api/lib/auth/scopes/index.js:15:14)
    at Session.isActive (web/node_modules/.pnpm/@shopify+shopify-api@7.0.0/node_modules/@shopify/shopify-api/lib/session/session.js:74:79)
    at/web/node_modules/.pnpm/@shopify+shopify-app-express@1.2.2/node_modules/@shopify/shopify-app-express/build/cjs/middlewares/validate-authenticated-session.js:58:21


```

## Steps to reproduce the problem

1.
1.
1.

**Comment by mkevinosullivan** [comment]
@schapicool Please advise how you're reproducing this?  What database/database adapter are you using?
