### ISSUE TITLE
Error during OAuth process but the app is still installed

### ISSUE THREAD

**Issue by hoangminhtuan1399** [Shopify/shopify-api-js#896]
# Issue summary

I'm developing an app. when installing my app to the development store, I get this error on the terminal: 

```
2023-05-31 06:46:51 | backend    | [shopify-app/INFO] Running ensureInstalledOnShop
2023-05-31 06:46:51 | backend    | [shopify-app/INFO] App is installed and ready to load | {shop: net-development-store.myshopify.com}
2023-05-31 06:47:51 | backend    | [shopify-app/INFO] Running ensureInstalledOnShop
2023-05-31 06:47:51 | backend    | [shopify-app/INFO] Found a session, but it is not valid. Redirecting to auth | {shop: net-development-store.myshopify.com}
2023-05-31 06:47:51 | backend    | [shopify-api/INFO] Beginning OAuth | {shop: net-development-store.myshopify.com, isOnline: false, callbackPath: /api/auth/callback}
2023-05-31 06:47:56 | backend    | [shopify-app/INFO] Handling request to complete OAuth process
2023-05-31 06:47:56 | backend    | [shopify-api/INFO] Completing OAuth | {shop: net-development-store.myshopify.com}
2023-05-31 06:47:57 | backend    | [shopify-api/INFO] Creating new session | {shop: net-development-store.myshopify.com, isOnline: false}
2023-05-31 06:47:57 | backend    | [shopify-api/INFO] Registering webhooks | {shop: net-development-store.myshopify.com}
2023-05-31 06:47:57 | backend    | [shopify-api/WARNING] API Deprecation Notice 5/31/2023, 1:47:57 PM : 
                                   {"message":"https://shopify.dev/api/usage/versioning#deprecation-practices","path":"https://net-development-store.myshopify.com/admin/api/2023-01/graphql.json","body":"{\n  webhookSubscriptions(\n    first: 250,\n    after: null,\n
                                     ) {\n    edges {\n      node {\n        id..."}  -  Stack Trace: Error
2023-05-31 06:47:57 | backend    |     at NewHttpClient.<anonymous> (/home/tuan/work/htdocs/shopify-app-product-options/web/node_modules/@shopify/shopify-api/lib/clients/http_client/http_client.js:267:33)
2023-05-31 06:47:57 | backend    |     at step (/home/tuan/work/htdocs/shopify-app-product-options/web/node_modules/tslib/tslib.js:144:27)
2023-05-31 06:47:57 | backend    |     at Object.next (/home/tuan/work/htdocs/shopify-app-product-options/web/node_modules/tslib/tslib.js:125:57)
2023-05-31 06:47:57 | backend    |     at fulfilled (/home/tuan/work/htdocs/shopify-app-product-options/web/node_modules/tslib/tslib.js:115:62)
2023-05-31 06:47:57 | backend    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-05-31 06:47:58 | backend    | [shopify-app/ERROR] Failed to complete OAuth with error: Error: GraphQL query returned errors
```
It seems to be an issue during the OAuth process, however, if I click the 'Apps' on the admin navigation, my app is still installed and I can use it properly.

- `@shopify/shopify-api` version:
- Node version: 14.21.2
- Operating system: Ubuntu 20

## Expected behavior

If the app is installed, I don't have to go back to shopify admin to open it.

## Actual behavior

An error with the OAuth process occurs, but the app is still installed, I have to go back to shopify admin to use it.

## Steps to reproduce the problem

1. Install my app to the development store.
2. The error occurs.
3. Go back to shopify admin and open it.
4. Uninstall my app.
5. Reinstall my app.
6. The error occurs.

**Comment by hoangminhtuan1399** [comment]
Here is the error site after installing the app
![image](https://github.com/Shopify/shopify-api-js/assets/96128410/e57f6b88-28f2-4f62-96f8-f8eb79a8a244)

**Comment by hoangminhtuan1399** [comment]
Good day @paulomarg, after using node 16.20.0 which is compatible with the [@shopify/shopify-app-session-storage-mysql](https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-session-storage-mysql#readme), I still got this error.
```
import { BillingInterval, LATEST_API_VERSION } from '@shopify/shopify-api';
import { shopifyApp } from '@shopify/shopify-app-express';
import { MySQLSessionStorage } from '@shopify/shopify-app-session-storage-mysql';
import dotenv from 'dotenv';
import mysql from 'mysql2/promise';

dotenv.config();
let { restResources } = await import(
    `@shopify/shopify-api/rest/admin/2023-01`
    );
// If you want IntelliSense for the rest resources, you should import them directly
// import { restResources } from "@shopify/shopify-api/rest/admin/2022-10";

const MYSQL_USERNAME = process.env.MYSQL_USERNAME;
const MYSQL_PASSWORD = process.env.MYSQL_PASSWORD;
const MYSQL_HOST = process.env.MYSQL_HOST;
const MYSQL_DATABASE = process.env.MYSQL_DATABASE;

// The transactions with Shopify will always be marked as test transactions, unless NODE_ENV is production.
// See the ensureBilling helper to learn more about billing in this template.
const billingConfig = {
    'My Shopify One-Time Charge': {
        // This is an example configuration that would do a one-time charge for $5 (only USD is currently supported)
        amount: 5.0,
        currencyCode: 'USD',
        interval: BillingInterval.OneTime
    }
};

const shopify = shopifyApp({
    api: {
        apiVersion: LATEST_API_VERSION,
        restResources,
        billing: undefined // or replace with billingConfig above to enable example billing
    },
    auth: {
        path: '/api/auth',
        callbackPath: '/api/auth/callback'
    },
    webhooks: {
        path: '/api/webhooks'
    },
    // This should be replaced with your preferred storage strategy
    sessionStorage: new MySQLSessionStorage(
        new URL(`mysql://${MYSQL_USERNAME}:${MYSQL_PASSWORD}@${MYSQL_HOST}/${MYSQL_DATABASE}`)
    )
});

export default shopify;
```
Btw, there was an old version of my app using my mysql session storage and it worked fine. After implement some new features and updating app scopes, this error began to happen.
Old version scopes: 
```
scopes = "read_products, write_files, write_draft_orders"
```
New version scopes:
```
scopes = "read_products, write_files, read_discounts, write_draft_orders, read_customers"
```

**Comment by hoangminhtuan1399** [comment]
I found the problem. The was something wrong with the mysql query in my registered webhook's callback. After troubleshooting from there, I managed to fixed the error. Thanks for you advice @paulomarg. Should I close this issue?
