### ISSUE TITLE
RestResourceError: Could not find a path for request

### ISSUE THREAD

**Issue by supercoolspy** [Shopify/shopify-api-js#989]
# Issue summary

- `@shopify/shopify-api` version:
- Node version: 20 (pnpm)
- Operating system: Ubunut 22.04

```
[shopify-api/DEBUG] REST client has a redundant API version override to the default 2023-07
RestResourceError: Could not find a path for request
    at DiscountCode.getPath (/home/spy/Documents/mc-affiliated/node_modules/@shopify/shopify-api/rest/base.js:108:19)
    at DiscountCode.<anonymous> (/home/spy/Documents/mc-affiliated/node_modules/@shopify/shopify-api/rest/base.js:42:31)
    at Generator.next (<anonymous>)
    at /home/spy/Documents/mc-affiliated/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/spy/Documents/mc-affiliated/node_modules/tslib/tslib.js:165:16)
    at DiscountCode.request (/home/spy/Documents/mc-affiliated/node_modules/@shopify/shopify-api/rest/base.js:37:24)
    at NewResource.<anonymous> (/home/spy/Documents/mc-affiliated/node_modules/@shopify/shopify-api/rest/base.js:143:52)
    at Generator.next (<anonymous>)
    at /home/spy/Documents/mc-affiliated/node_modules/tslib/tslib.js:169:75
error: script "dev" exited with code 1 (SIGHUP)
```

## Expected behavior
client can save discount code

## Actual behavior
API cannot save discount code

## Steps to reproduce the problem

1. Create a new shopify dev app inside of a store
2. Set it up with the app secret key and rest recources
3. try to save a discount
```
shopifyApi({
        apiSecretKey: SECRET_KEY,
        apiVersion: ApiVersion.July23,
        isCustomStoreApp: true,
        adminApiAccessToken: ADMIN_API_TOKEN!!,
        isEmbeddedApp: false,
        hostName: "store.myshopify.com",
        logger: {
            level: LogSeverity.Debug,
            httpRequests: true, // if the error seems to be related to requests
        },
        restResources
    })
```

```
let api = newShopify() //calls above
let discount = new api.rest.DiscountCode({session})
discount.code = "test_code_yay"
discount.price_rule_id = 1626761625927
await discount.save({
            update: true
        })
```

**Comment by lizkenyon** [comment]
Hi there 👋 

It is common to get this error message if you are not including all of the required IDs to make the request.

For example @adearriba-fik you are not including the required [order_id.](https://shopify.dev/docs/api/admin-rest/2023-07/resources/fulfillment#get-orders-order-id-fulfillments)

 I have updated this error message to provide more context in these scenarios.
