### ISSUE TITLE
RestResourceError: Could not find a path for request when saving transaction

### ISSUE THREAD

**Issue by fabioportieri** [Shopify/shopify-api-js#992]
# Issue summary

<!--

i have this method in my remix shopify app, generated with the cli

```

import type { RestResources } from 'node_modules/@shopify/shopify-api/rest/admin/2023-07';
import type { Order } from 'node_modules/@shopify/shopify-api/rest/admin/2023-07/order';
import type { Transaction } from 'node_modules/@shopify/shopify-api/rest/admin/2023-07/transaction';
import type { AdminApiContext } from 'node_modules/@shopify/shopify-app-remix/build/ts/config-types';

export async function createSaleTransactionForOrder(
  admin: AdminApiContext,
  session: Session,
  order: Order
): Promise<Transaction> {
  const transaction: Transaction = new admin.rest.resources.Transaction({
    session,
    order_id: order.id,
    kind: 'sale', // Specify the transaction type as 'sale'
    amount: order.total_price,
    currency: order.currency,
    gateway: "Cash on Delivery (COD)",
    user_id: order.customer!.id
  });

  await transaction.save({
    update: true,
  });

  return transaction;
}```

i do a similar thing for Order resource and it works there

-->

- `@shopify/shopify-api` version: 7.6.0
- Node version: 9.50
- Operating system: linux / win11

```
RestResourceError: Could not find a path for request
22:21:49 │ remix │     at Function.getPath (/home/fabio/workspace/bulk-importer/node_modules/@shopify/shopify-api/rest/base.ts:201:13)
22:21:49 │ remix │     at Function.<anonymous> (/home/fabio/workspace/bulk-importer/node_modules/@shopify/shopify-api/rest/base.ts:110:23)
22:21:49 │ remix │     at Generator.next (<anonymous>)
22:21:49 │ remix │     at /home/fabio/workspace/bulk-importer/node_modules/tslib/tslib.js:169:75
22:21:49 │ remix │     at new Promise (<anonymous>)
22:21:49 │ remix │     at Object.__awaiter (/home/fabio/workspace/bulk-importer/node_modules/tslib/tslib.js:165:16)
22:21:49 │ remix │     at Function.request (/home/fabio/workspace/bulk-importer/node_modules/@shopify/shopify-api/rest/base.js:37:24)
22:21:49 │ remix │     at RemixResource.<anonymous> (/home/fabio/workspace/bulk-importer/node_modules/@shopify/shopify-api/rest/base.ts:266:44)
22:21:49 │ remix │     at Generator.next (<anonymous>)
22:21:49 │ remix │     at /home/fabio/workspace/bulk-importer/node_modules/tslib/tslib.js:169:75
22:21:49 │ remix │ Could not find a path for request
```

## Expected behavior

save the transaction with no errors

## Actual behavior

the error

**Comment by fabioportieri** [comment]
can be closed, this is the correct syntax
```
export async function createSaleTransactionForOrder(
  admin: AdminApiContext,
  session: Session,
  order: Order
): Promise<Transaction> {
  console.log("🚀 creating transaction with following values, order_id:", order.id, " order price: ", order.total_price, " customer id: ", order.customer!.id, " currency: ", order.currency);

  const transaction: Transaction = new admin.rest.resources.Transaction({
    session
  });
  
  transaction.order_id = order.id;
  transaction.kind = 'sale'; // Specify the transaction type as 'sale;
  transaction.amount = order.total_price;
  transaction.currency = order.currency;
  transaction.gateway = "Cash on Delivery (COD)";
  transaction.user_id = order.customer!.id;

  await transaction.save({
    update: true,
  });

  return transaction;
}
```
